package memoria;

import java.awt.Color;

public class telaInicial extends javax.swing.JFrame {

    ReproduzAudio ReproduzAudio = new ReproduzAudio();

    /**
     * Creates new form telaInicial
     */
    public telaInicial() {
        initComponents();
        ReproduzAudio.playAudio("src\\memoria\\audio\\menu.wav");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgImage = new javax.swing.JLabel();
        selecioneNivel = new javax.swing.JLabel();
        facil = new javax.swing.JButton();
        medio = new javax.swing.JButton();
        dificil = new javax.swing.JButton();
        bgImageMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sustainable Memory 1.0");
        setBounds(new java.awt.Rectangle(400, 130, 0, 0));
        setMinimumSize(new java.awt.Dimension(555, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memoria/imagens/tela_inicial.png"))); // NOI18N
        bgImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bgImageMouseClicked(evt);
            }
        });
        getContentPane().add(bgImage);
        bgImage.setBounds(0, 0, 555, 500);

        selecioneNivel.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        selecioneNivel.setForeground(new java.awt.Color(255, 255, 255));
        selecioneNivel.setText("Selecione o nível");
        getContentPane().add(selecioneNivel);
        selecioneNivel.setBounds(130, 90, 290, 60);

        facil.setBackground(new java.awt.Color(0, 82, 0));
        facil.setFont(new java.awt.Font("Comic Sans MS", 1, 22)); // NOI18N
        facil.setForeground(new java.awt.Color(255, 255, 255));
        facil.setText("Fácil");
        facil.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 51), 3, true));
        facil.setBorderPainted(false);
        facil.setFocusPainted(false);
        facil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facilMouseExited(evt);
            }
        });
        getContentPane().add(facil);
        facil.setBounds(235, 175, 80, 30);

        medio.setBackground(new java.awt.Color(0, 82, 0));
        medio.setFont(new java.awt.Font("Comic Sans MS", 1, 22)); // NOI18N
        medio.setForeground(new java.awt.Color(255, 255, 255));
        medio.setText("Médio");
        medio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 51), 3, true));
        medio.setBorderPainted(false);
        medio.setFocusPainted(false);
        medio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                medioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                medioMouseExited(evt);
            }
        });
        getContentPane().add(medio);
        medio.setBounds(235, 245, 80, 30);

        dificil.setBackground(new java.awt.Color(0, 82, 0));
        dificil.setFont(new java.awt.Font("Comic Sans MS", 1, 22)); // NOI18N
        dificil.setForeground(new java.awt.Color(255, 255, 255));
        dificil.setText("Difícil");
        dificil.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 51), 3, true));
        dificil.setBorderPainted(false);
        dificil.setFocusPainted(false);
        dificil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dificilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dificilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dificilMouseExited(evt);
            }
        });
        getContentPane().add(dificil);
        dificil.setBounds(235, 315, 80, 30);

        bgImageMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memoria/imagens/tela_menu.png"))); // NOI18N
        getContentPane().add(bgImageMenu);
        bgImageMenu.setBounds(0, 0, 555, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void bgImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgImageMouseClicked
        bgImage.setVisible(false);
    }//GEN-LAST:event_bgImageMouseClicked

    private void medioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medioMouseEntered
        // TODO add your handling code here:
        medio.setBackground(new Color(0, 102, 0));
        medio.setBounds(230, 240, 90, 40);
    }//GEN-LAST:event_medioMouseEntered

    private void medioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medioMouseExited
        // TODO add your handling code here:
        medio.setBackground(new Color(0, 82, 0));
        medio.setBounds(235, 245, 80, 30);
    }//GEN-LAST:event_medioMouseExited

    private void dificilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dificilMouseEntered
        // TODO add your handling code here:
        dificil.setBackground(new Color(0, 102, 0));
        dificil.setBounds(230, 310, 90, 40);
    }//GEN-LAST:event_dificilMouseEntered

    private void dificilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dificilMouseExited
        // TODO add your handling code here:
        dificil.setBackground(new Color(0, 82, 0));
        dificil.setBounds(235, 315, 80, 30);
    }//GEN-LAST:event_dificilMouseExited

    private void facilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facilMouseEntered
        // TODO add your handling code here:
        facil.setBackground(new Color(0, 102, 0));
        facil.setBounds(230, 170, 90, 40);
    }//GEN-LAST:event_facilMouseEntered

    private void facilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facilMouseExited
        // TODO add your handling code here:
        facil.setBackground(new Color(0, 82, 0));
        facil.setBounds(235, 175, 80, 30);
    }//GEN-LAST:event_facilMouseExited

    private void facilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facilMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Memoria jogo = new Memoria(16, 1, "Fácil");
        jogo.setVisible(true);
    }//GEN-LAST:event_facilMouseClicked

    private void medioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medioMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Memoria jogo = new Memoria(24, 7, "Médio");
        jogo.setVisible(true);
    }//GEN-LAST:event_medioMouseClicked

    private void dificilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dificilMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Memoria jogo = new Memoria(36, 29, "Difícil");
        jogo.setVisible(true);
    }//GEN-LAST:event_dificilMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImage;
    private javax.swing.JLabel bgImageMenu;
    private javax.swing.JButton dificil;
    private javax.swing.JButton facil;
    private javax.swing.JButton medio;
    private javax.swing.JLabel selecioneNivel;
    // End of variables declaration//GEN-END:variables
}
